VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ScriptFunction"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Public Name As String
Public ReturnsValue As Boolean
Public Variables As Collection
Public Arguments As Collection

Private Sub Class_Initialize()
On Error Resume Next
    Set Variables = New Collection
    Set Arguments = New Collection
End Sub
