VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "GameDebugger"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'
'    libDebugger (Fury² Game Creation System Debugging Thunk)
'    Copyright (C) 2003 Kevin Gadd
'
'    This library is free software; you can redistribute it and/or
'    modify it under the terms of the GNU Lesser General Public
'    License as published by the Free Software Foundation; either
'    version 2.1 of the License, or (at your option) any later version.
'
'    This library is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
'    Lesser General Public License for more details.
'
'    You should have received a copy of the GNU Lesser General Public
'    License along with this library; if not, write to the Free Software
'    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
'

Option Explicit
Public Hook As Object
Public Engine As Fury2Engine
Private m_engDefault As Fury2Engine

Public Property Get GameEngine() As Object
On Error Resume Next
    Set GameEngine = Engine
End Property

Public Sub LoadGame(ByRef Path As String)
On Error Resume Next
    Set m_engDefault = DefaultEngine
    Fury2Load Path, EM_Normal, Me, Hook, Engine
End Sub

Public Sub Begin()
On Error Resume Next
    Set DefaultEngine = m_engDefault
End Sub
