VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Fury2VideoEventSink"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Sub KeyDown(ByVal KeyCode As Integer, ByVal Shift As Integer)
End Sub

Sub KeyPress(ByVal KeyAscii As Integer)
End Sub

Sub KeyUp(ByVal KeyCode As Integer, ByVal Shift As Integer)
End Sub

Sub MouseDown(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
End Sub

Sub MouseMove(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
End Sub

Sub MouseUp(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
End Sub

Sub Paint()
End Sub

Sub Closed()
End Sub

Sub Resize()
End Sub

Sub DblClick()
End Sub
