VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Fury2UserdataUI"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Sub Redraw(ByVal Surface As Fury2Image)
On Error Resume Next
End Sub

Public Sub MouseDown(ByVal Button As Long, ByVal Shift As Long, ByVal X As Long, ByVal Y As Long)
On Error Resume Next
End Sub

Public Sub MouseMove(ByVal Button As Long, ByVal Shift As Long, ByVal X As Long, ByVal Y As Long)
On Error Resume Next
End Sub

Public Sub MouseUp(ByVal Button As Long, ByVal Shift As Long, ByVal X As Long, ByVal Y As Long)
On Error Resume Next
End Sub

Public Sub KeyDown(ByVal Key As Long, ByVal Shift As Long)
On Error Resume Next
End Sub

Public Sub KeyPress(ByVal Character As Long)
On Error Resume Next
End Sub

Public Sub KeyUp(ByVal Key As Long, ByVal Shift As Long)
On Error Resume Next
End Sub

Public Property Get This() As Object
On Error Resume Next
End Property
